### ISSUE TITLE
custom profile is broken with tuned-2.5.1

### ISSUE THREAD

**Issue by ghost** [thias/puppet-tuned#17]
following the example I provide a custom profile in puppet like

``` puppet
class { '::tuned':
  profile => 'my-super-tweaks',
  source  => 'puppet:///modules/mymodule/tune-profiles/my-super-tweaks',
}
```

This results in a file created at `/etc/tuned/` called `my-super-tweaks`.  This is not recognized by tuned as a valid profile. 

The tool expects instead a folder in `/etc/tuned` with the profile name and a file called `tuned.conf` inside with the profile tweaks. eg. `/etc/tuned/my-super-tweaks/tuned.conf`

Documentation [here](https://fedorahosted.org/tuned/).

**Comment by ggeldenhuis** [comment]
@nbalonso the documentation link is no longer active. To be clear I am not working on this issue, just another interested party in breathing life into this module again.

**Comment by nbalonso** [comment]
If you are looking for the documentation, see [this](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/performance_tuning_guide/index#custom-profiles) or [this](https://access.redhat.com/solutions/1305833)

The second link explains it better but it requires an account with redhat

**Comment by thias** [comment]
I'm updating the README to make it clear that `$source` must be a directory and not the single `tuned.conf` file. That directory may contain only that file, but also some additional required scripts.
