### ISSUE TITLE
Scripts in Custom Profiles are not Executable

### ISSUE THREAD

**Issue by ahackett** [thias/puppet-tuned#19]
Hi

In order for scripts in custom profiles to work, they must be executable. However, init.pp specifies a mode of 0644 for files in the profile file tree. This means the script isn't executed when the custom profile is made active, and thus it doesn't work as intended.

A quick fix is to change line 57 in init.pp from

`mode    => '0644'`

to 

`mode    => '0744'`

**Comment by ITD27M01** [comment]
I have the same issue. The source of this the following:
https://github.com/thias/puppet-tuned/blob/master/manifests/init.pp#L57

**Comment by thias** [comment]
Instead of changing the `tuned.conf` of all existing deployments to become +x, I have added a `$scripts` parameter which changes the mode to 0755 when set to true.
