### ISSUE TITLE
Modifications to tuned profile should trigger a refresh

### ISSUE THREAD

**Issue by treydock** [thias/puppet-tuned#8]
Unsure how exactly this is best handled with tuned.  If a profile is modified, should that File resource notify the tuned service to restart?

Happy to submit PR just unsure best way to handle changes to a tuned profile.

**Comment by thias** [comment]
I think that would be the way, yes, so it should be trivial. If this is something you're interested in, then please test the change and submit a PR!

**Comment by thias** [comment]
This should now be fixed in 4791758c73e7752e6c91853d9c66d3f2a71ffa5b and in the upcoming 1.0.2 release.
