### ISSUE TITLE
module metadata out of date

### ISSUE THREAD

**Issue by jcpunk** [thias/puppet-tuned#9]
Your module score on the forge is artificially low due to metadata issues.

Can you update this module according to https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#write-a-metadatajson-file

**Comment by thias** [comment]
Correct! This has been fixed in bd77a627a493a6c486240ac5ca54bfdbce46f64a and released in 1.0.1, which now has a score of 5.0 :-)
